# Generated by Django 4.1.4 on 2024-08-22 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nexus', '0002_rename_follow_profile_follows_profile_date_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='nux', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
