# Generated by Django 4.1.4 on 2024-08-25 07:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nexus', '0005_profile_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='nex_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
