# Generated by Django 4.1.4 on 2024-08-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0007_remove_profile_likes_nux_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_bio',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='snapchat_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
